//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CraigslistStudy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Term
    {
        public int Id { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string TermText { get; set; }
        public Nullable<int> Rank { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
    }
}
